services:
    app:
        image: hanabosocom/go-base:1.24
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/app
            - ${GOPATH}/pkg:/go/pkg
            - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
        environment:
            DEV_UID: ${DEV_UID}
            DEV_GID: ${DEV_GID}
            MONGO_DSN: mongodb://mongodb/database?connectTimeoutMS=2500&serverSelectionTimeoutMS=2500&socketTimeoutMS=2500&heartbeatFrequencyMS=2500

    mongodb:
        image: mongo:latest
        container_name: go-mongodb-mongodb
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongodb:/data/db

volumes:
    mongodb:
